services:
  php-engine:
    image: php:8.2-apache
    container_name: php_server
    ports:
      - "80:80" #use port 80 default
    volumes:
      - ./php:/var/www/html
    networks:
      - backend-network

  #mySQL database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=recipe_database
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network

  #phpMyAdmin image
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_tool
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=""
      - PMA_USER=root
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
